### ISSUE TITLE
traceback problem

### ISSUE THREAD

**Issue by soroko77** [SpectralVectors/GhibliGenerator#1]
I appreciate your beautiful assets.

Is it only available for 3.2?
I'm using 3.1 ver.
Any assets that are not available except for a few
I think there are quite a few.
Is there a problem with how to use it?

Python: Traceback
 
KeyError: 'bpy_prop_collection[key]: key "Array" not found'

**Comment by SpectralVectors** [comment]
OK, I don't have a copy of 3.1, but I ran some tests in 2.93 and I think I was getting the same issues as you, traceback errors when creating certain objects.

The problem seems to be with the creation of the driver panels, not the assets themselves.

Some of the assets are setup with a Custom Properties panel to access things like color, scale etc from the 3D viewport. It looks like they changed some of the Python commands for creating the panel. I'm probably not able to code a solution for at least a week or so, but the good news is the assets should all work, and look exactly as they're supposed to, you just may have to go into the Shader Editor to adjust some settings.

I'll leave the issue open for now, in case this wasn't the same thing you were experiencing, but if it's the same Traceback that I was getting, then you should still be able to use the assets, even with the error.

**Comment by tctcwo** [comment]
Python:Traceback(most recent call last):
File "C:\Users\tctcwo\AppData\RoamingBlender Foundation\Blender\4.GroundPlaneslGrassPlane.py",line 92,in execute
assignDrivers()
File "C:\Usersltctcwo\AppData\Roaming\Blender FoundationBlender\4.1\scriptsladdonslGhibliGIndPlanes\Drivers\GrassPlaneDrivers.py",line 291,in assignDriversdriver = d['driven obiect'l.driver add(d['driven value'l, d['index'])
TypeError: bpy_struct.driver_add(): property "nodes["ColorRamp"].color_ramp.elements[0].color" not found
